[config]
schemaVersion = "0.0.1"

[package]
namespace = "AuthorName"
name = "PackageName"
description = "Example mod description"
websiteUrl = "https://github.com/funlennysub/MycopunkModTemplate"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Mycopunk = "5.4.2403"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

[[build.copy]]
source = "bin/Release/netstandard2.1/MycopunkModTemplate.dll"
target = "BepInEx/plugins/MycopunkModTemplate.dll"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE"
target = "LICENSE"

[publish]
repository = "https://thunderstore.io"
communities = [ "mycopunk" ]

[publish.categories]
mycopunk = [ "client" ]


